 
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - dockerwp

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockerwp
  apache:
    image: bitnami/apache:2.4
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=eva.montecino.tech
      - LETSENCRYPT_HOST=eva.montecino.tech
      - LETSENCRYPT_EMAIL=xavi@kpyvara.com
    networks:
      - dockerwp
    restart: always
  networks:
  dockerwp:
volumes:
  certs:
  html:
  vhostd:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local


          - VIRTUAL_HOST=eva.montecino.tech
      - LETSENCRYPT_HOST=eva.montecino.tech
      - LETSENCRYPT_EMAIL=xavi@kpyvara.com