version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - dockerwp

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockerwp
  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./google3a2b0e8834a6778b.html:/var/www/html   
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php.ini:/var/www/html/wp-admin/php.ini
    expose:
      - 80
    environment:
    networks:
      - dockerwp
    restart: always
      
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - VIRTUAL_HOST=montecino.tech
      - LETSENCRYPT_HOST=montecino.tech
      - LETSENCRYPT_EMAIL=oxmonteroc83@est.ucacue.edu.ec
    export:
      - 80
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
   networks:
      - dockerwp
    restart: always
networks:
  dockerwp:
volumes:
  certs:
  html:
  vhostd:
  wordpress:
  mariadb:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

 
